export const modalClasses = {
  root: "Modal-root",
  backdrop: "Modal-backdrop",
  opened: "Modal-opened",
  content: "Modal-content",
  buzzable: "Modal-buzzable",
  slide: "Modal-slide",
  zoom: "Modal-zoom",
  fade: "Modal-fade",
  header: "Modal-header",
  title: "Modal-title",
  close: "Modal-close",
  body: "Modal-body",
  footer: "Modal-footer",
};
